### ISSUE TITLE
Solucionar el problema al consumir datos de ELASTICC

### ISSUE THREAD

**Issue by dirodriguezm** [alercebroker/sorting_hat_step#55]
```
Traceback (most recent call last):
  File "run_step.py", line 43, in <module>
    step.start()
  File "/usr/local/lib/python3.8/site-packages/apf/core/step.py", line 370, in start
    for message in self.consumer.consume():
  File "/usr/local/lib/python3.8/site-packages/apf/consumers/kafka.py", line 235, in consume
    message = self._deserialize_message(message)
  File "/usr/local/lib/python3.8/site-packages/apf/consumers/kafka.py", line 162, in _deserialize_message
    reader = fastavro.reader(bytes_io)
  File "fastavro/_read.pyx", line 1055, in fastavro._read.reader.__init__
  File "fastavro/_read.pyx", line 1006, in fastavro._read.file_reader.__init__
  File "fastavro/_read.pyx", line 741, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 613, in fastavro._read.read_record
  File "fastavro/_read.pyx", line 725, in fastavro._read._read_data
  File "fastavro/_read.pyx", line 468, in fastavro._read.read_map
  File "fastavro/_read.pyx", line 299, in fastavro._read.read_utf8
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1-2: invalid continuation byte
```

```[tasklist]
### Tasks
- [ ] https://github.com/alercebroker/APF/issues/60
- [ ] https://github.com/alercebroker/APF/issues/61
- [ ] https://github.com/alercebroker/sorting_hat_step/issues/56
- [ ] https://github.com/alercebroker/kubernetes_pipeline/issues/93
```
